server:
  port: 8080

spring:
  application:
    name: ${APP_NAME}
  jpa:
    database: postgresql
    open-in-view: false
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://db:5432/${POSTGRES_DB}?currentSchema=public
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yml
    contexts: default
    default-schema: public

springdoc:
  cache:
    disabled: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

security:
  access-token:
    jwk: ${ACCESS_TOKEN_JWK}
    expiration: ${ACCESS_TOKEN_EXPIRATION}
  refresh-token:
    jwk: ${REFRESH_TOKEN_JWK}
    expiration: ${REFRESH_TOKEN_EXPIRATION}
  crypto:
    aes-key-base64: ${AES_KEY_BASE64}